# include paths don't need to be wrapped in quotes, but it makes it easier to differentiate

# relative includes are supported. For example:
# if your local config is in a separate local-testing-configs directory in the project root
# add `../configs/` in front of each of the include paths

# include one duck without overrides ($include doesn't copy in the key)
one-duck:
  standard-rubber-duck:
    $include: "production-config.yaml@$.ducks.standard-rubber-duck"

# override usage
override-duck:
  standard-rubber-duck:
    $include: "production-config.yaml@$.ducks.standard-rubber-duck"
    settings:
      agent:
        engine: gpt-5-nano

# include all ducks with example override
all-ducks:
  $include: "production-config.yaml@$.ducks"
  standard-rubber-duck:
    settings:
      agent:
        engine: gpt-5-nano

# include multiple specific ducks
multiple-ducks:
  standard-rubber-duck:
    $include: "production-config.yaml@$.ducks.standard-rubber-duck"
  stats-duck:
    $include: "production-config.yaml@$.ducks.stats-duck"

# multiple includes are also supported (the second include can override a portion of the first
multiple-includes:
  standard-rubber-duck:
    $include_0: "production-config.yaml@$.ducks.standard-rubber-duck"
    $include_1: "production-config.yaml@$.ducks.stats-duck"

# including strings also works, but there can't be any additional keys below the $include key
string-include:
  $include: "production-config.yaml@$.sender_email"

# ========== STARTER CONFIG TEMPLATE ========== #

sql:
  db_type: sqlite
  database: local-testing-configs/local_<name>_database.db

ducks:
  standard-rubber-duck:
    $include: "production-config.yaml@$.ducks.standard-rubber-duck"

servers:
  BeanLab:
    server_id: <server_id>
    channels:
      Ducks/<name>-chat-bot:
        channel_id: <channel_id>
        timeout: 300
        duck: standard-rubber-duck

agents_as_tools:
  $include: "production-config.yaml@$.agents_as_tools"

sender_email:
  $include: "production-config.yaml@$.sender_email"

admin_settings:
  $include: "production-config.yaml@$.admin_settings"
  admin_channel_id: <admin_channel_id>
  admin_role_id: <admin_role_id>

ai_completion_retry_protocol:
  $include: "production-config.yaml@$.ai_completion_retry_protocol"

reporter_settings:
  $include: "production-config.yaml@$.reporter_settings"

cache_cleanup_settings:
  $include: "production-config.yaml@$.cache_cleanup_settings"

# ============================================== #
