name: Build, Push, and Deploy to AWS Infrastructure

on:
  push:
    branches:
      - master
      - 110-fargate-update
  workflow_dispatch:
    inputs:
      local_config:
        description: "Path to local config file to upload (e.g., wiley-config.json)"
        required: false
        default: "infra/config.json"
        type: string

jobs:
  send_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create secrets file
        run: |
          cat > secrets.env << EOL
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          CANVAS_TOKEN=${{ secrets.CANVAS_TOKEN }}
          COURSE_ID=${{ secrets.COURSE_ID }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          ENVIRONMENT="production"
          EOL

      - name: Validate config file
        run: |
          # Debug current directory and file existence
          echo "Current directory: $(pwd)"
          echo "Looking for config file: ${{ inputs.local_config || 'infra/config.json' }}"
          ls -la infra/

          # Check if file exists
          if [ ! -f "${{ inputs.local_config || 'infra/config.json' }}" ]; then
            echo "Error: Config file '${{ inputs.local_config || 'infra/config.json' }}' not found"
            echo "Available files in infra directory:"
            ls -la infra/
            exit 1
          fi
          echo "Config file validated successfully"

      - name: Upload config and secrets to S3
        run: |
          # Get branch name and SHA for unique naming
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)

          # Create unique names for the files
          CONFIG_NAME="${BRANCH_NAME}-${SHORT_SHA}-${TIMESTAMP}.json"
          SECRETS_NAME="${BRANCH_NAME}-${SHORT_SHA}-${TIMESTAMP}.env"

          # Debug file paths
          echo "Config file path: ${{ inputs.local_config || 'infra/config.json' }}"
          echo "Target S3 path: s3://rubber-duck-config/${CONFIG_NAME}"

          # Upload files
          aws s3 cp "${{ inputs.local_config || 'infra/config.json' }}" "s3://rubber-duck-config/${CONFIG_NAME}"
          aws s3 cp secrets.env "s3://rubber-duck-config/${SECRETS_NAME}"

          # Set outputs for use in other jobs
          echo "CONFIG_S3_PATH=s3://rubber-duck-config/${CONFIG_NAME}" >> $GITHUB_ENV
          echo "SECRETS_S3_PATH=s3://rubber-duck-config/${SECRETS_NAME}" >> $GITHUB_ENV

          echo "Uploaded config to: s3://rubber-duck-config/${CONFIG_NAME}"
          echo "Uploaded secrets to: s3://rubber-duck-config/${SECRETS_NAME}"

  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.extract_sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

      - name: Extract short SHA
        id: extract_sha
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}"  # Debugging
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-5)
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "::set-output name=short_sha::${SHORT_SHA}"
          echo "Extracted SHORT_SHA: ${SHORT_SHA}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker build script
        run: bash ./infra/build_docker.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck

      - name: Tag and Push Docker Image
        run: |
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}"
          echo "Tagging image as: $IMAGE_TAG"

          docker tag 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:latest \
            844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$IMAGE_TAG

          docker push 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$IMAGE_TAG

      - name: Complete Docker push
        run: echo "Docker image pushed to ECR with tag ${BRANCH_NAME}-${SHORT_SHA}!"

  deploy_to_cloudformation:
    needs: [build_and_push, send_config]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS Infrastructure with CloudFormation
        id: deploy
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${{ needs.build_and_push.outputs.short_sha }}"
          echo "Deploying ECS with image tag: ${IMAGE_TAG}"

          aws cloudformation deploy \
            --stack-name rubber-duck-production \
            --template-file infra/ecs-infra.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            Environment=production \
            ClusterName=DuckCluster-rubber-duck-production \
            TaskDefinitionFamily=rubber-duck-production \
            ContainerName=duck-container-production \
            "ImageURI=844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:${IMAGE_TAG}" \
            "VpcId=${{ secrets.VPC_ID }}" \
            "SubnetIds=${{ secrets.SUBNET_IDS }}" \
            "SecurityGroupId=${{ secrets.SECURITY_GROUP_ID }}" \
            "ExecutionRoleArn=${{ secrets.EXECUTION_ROLE }}" \
            "TaskRoleArn=${{ secrets.EXECUTION_ROLE }}" \
            "Cpu=1024" \
            "Memory=2048" \
            "EnvFileS3Path=${{ needs.send_config.outputs.SECRETS_S3_PATH }}" \
            "ConfigFileS3Path=${{ needs.send_config.outputs.CONFIG_S3_PATH }}"
