name: Build, Push, and Deploy to AWS Infrastructure

on:
  push:
    branches:
      - master
      - ECS-Teardown
  workflow_dispatch:
    inputs:
      local_config:
        description: "Path to local config file to upload"
        required: false
        type: string

jobs:
  extract_sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.extract_sha.outputs.short_sha }}
      extract_branch: ${{ steps.extract_branch.outputs.branch_name }}
      combined: ${{ steps.short_sha_and_branch_name.outputs.combined }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' | tr -cd '[:alnum:]-')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Extract short SHA
        id: extract_sha
        run: |
          SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-5)
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Combine short SHA and Branch Name
        id: short_sha_and_branch_name
        run: |
          COMBINED="${BRANCH_NAME}-${SHORT_SHA}"
          echo "COMBINED=${COMBINED}" >> $GITHUB_ENV
          echo "combined=${COMBINED}" >> $GITHUB_OUTPUT

  build_and_push:
    runs-on: ubuntu-latest
    environment: pre-production
    needs: extract_sha
    outputs:
      docker_image_tag: ${{ steps.set_outputs.outputs.docker_image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker build script
        run: bash .github/scripts/build_docker.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck

      - name: Tag and Push Docker Image
        id: set_outputs
        run: |
          IMAGE_TAG="${{ needs.extract_sha.outputs.combined }}"
          echo "Tagging image as: $IMAGE_TAG"

          docker tag 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:latest \
            844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$IMAGE_TAG

          docker push 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$IMAGE_TAG

          # ✅ Set the output for use in other jobs
          echo "docker_image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Complete Docker push
        run: echo "Docker image pushed to ECR with tag ${{ needs.extract_sha.outputs.combined }}!"

  send_sha_via_discord_webhook:
    runs-on: ubuntu-latest
    needs: [extract_sha, build_and_push]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send SHA to Discord Webhook
        run: |
          COMBINED="${{ needs.extract_sha.outputs.combined }}"
          DISCORD_WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          MESSAGE="✅ Deployment successfully to ECR!\n\n\`\`\`md\n$COMBINED\n\`\`\`\n\n"
          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g')
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$ESCAPED_MESSAGE\"}" "$DISCORD_WEBHOOK_URL"
