name: Build, Push, and Deploy to AWS Infrastructure

on:
  push:
    branches:
      - master  # Production
      - 62-aws-s3-and-fargate-deployment    # Test
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set environment variables
        run: bash .github/workflows/set-env.sh

      - name: Run Docker build script
        run: bash ./build_docker.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          if [[ "${{ env.IMAGE_TAG }}" == "test-latest" ]]; then
            TAG="test-latest"
          elif [[ "${{ env.IMAGE_TAG }}" == "latest" ]]; then
            TAG="production-latest"
          else
            echo "No valid tag found. Skipping push."
            exit 0
          fi
      
          docker tag 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:${{ env.IMAGE_TAG }} \
                     844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$TAG
          docker push 844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:$TAG


      - name: Complete Docker push
        run: echo "Docker images pushed to ECR successfully!"
    outputs:
      environment: ${{ steps.set_env_vars.outputs.environment }}
      image_tag: ${{ steps.set_env_vars.outputs.image_tag }}

  deploy_to_cloudformation:
    needs: [ build_and_push ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: What is the environment?
        run: echo "Environment is ${{ needs.build_and_push.outputs.environment }}"

      - name: Deploy ECS Infrastructure with CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name rubber-duck-${{ needs.build_and_push.outputs.environment }} \
            --template-file infra/ecs-infra.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              Environment=${{ needs.build_and_push.outputs.environment }} \
              ClusterName=DuckCluster-${{ needs.build_and_push.outputs.environment }} \
              TaskDefinitionFamily=rubber-duck-${{ needs.build_and_push.outputs.environment }} \
              ContainerName=duck-container-${{ needs.build_and_push.outputs.environment }} \
              ImageURI=844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:${{ needs.build_and_push.outputs.image_tag }}

      - name: Register ECS Task Definition and Deploy
        run: |
          bash .github/workflows/esc_setup.sh \
            "DuckCluster-${{ needs.build_and_push.outputs.environment }}" \
            "DuckService-${{ needs.build_and_push.outputs.environment }}" \
            "rubber-duck-${{ needs.build_and_push.outputs.environment }}" \
            "844825014198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beanlab/rubber-duck:${{ needs.build_and_push.outputs.image_tag }}" \
            "${{ secrets.AWS_REGION }}" \
            "${{ secrets.EXECUTION_ROLE }}" \
            "${{ secrets.ENV_FILE_S3_PATH }}"

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster DuckCluster-${{ needs.build_and_push.outputs.environment }} \
            --service DuckService-${{ needs.build_and_push.outputs.environment }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: Check ECS Service Status
        run: |
          aws ecs describe-services \
            --cluster DuckCluster-${{ needs.build_and_push.outputs.environment }} \
            --services DuckService-${{ needs.build_and_push.outputs.environment }} \
            --region ${{ secrets.AWS_REGION }}
