name: Pull and Test Docker Image

on:
  workflow_dispatch:

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 844825014198.dkr.ecr.us-west-2.amazonaws.com

      - name: Pull Docker image from ECR
        run: docker pull 844825014198.dkr.ecr.us-west-2.amazonaws.com/beanlab/rubber-duck:latest

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name rubber-duck-container --log-driver json-file --log-opt path=/var/log/docker/rubber-duck-container.log -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} 844825014198.dkr.ecr.us-west-2.amazonaws.com/beanlab/rubber-duck:latest

      - name: Check Docker container logs
        run: docker logs rubber-duck-container > rubber-duck-container.log

      - name: Stop and remove Docker container
        run: |
          docker stop rubber-duck-container
          docker rm rubber-duck-container
