name: Update Production Config

on:
  push:
    branches:
      - ECS-Teardown
  workflow_dispatch:

jobs:
  update_the_production_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Production Config
        run: bash .github/scripts/upload-config.sh ${{secrets.S3_LOCAL_PRODUCTION_CONFIG_PATH}} ${{secrets.S3_BUCKET_NAME}} ${{secrets.S3_KEY}}

  discord_notification:
    runs-on: ubuntu-latest
    needs: update_the_production_config
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit info
        id: commit_info
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Send notification to Discord
        run: |
          DISCORD_WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          COMMIT_SHA="${{ steps.commit_info.outputs.sha }}"
          COMMIT_MSG="${{ steps.commit_info.outputs.message }}"
          MESSAGE="✅ The production config has been successfully updated.\n\nCommit: \`$COMMIT_SHA\`\nMessage: \`$COMMIT_MSG\`"
          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g')
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$ESCAPED_MESSAGE\"}" "$DISCORD_WEBHOOK_URL"
